# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31944b910a20026407779e41974dc9a7b8ab61370509bce73470706d1ea20b48c11904fbaa1cda537c2a6e28310e89a10d2477413f14a664136c146d69d3be47

test:
  secret_key_base: 88a8e154c76890ca7cdeff3f2307aa65b3a85c1ece198d97f8990cd2ff20a3bdcc0f067fbe4c5b385876391abfef69780c8df5f870f45ca2726931c93f6ee4b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
